from __future__ import annotations

import hashlib
import json
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.errors import EvidencePlaneError
from app.models.db import AdvisorFinding, Case, Run, utc_now
from app.models.schemas import AdvisorFindingResponse

_MODEL_PROVIDER = "anthropic"
_MODEL_VERSION = "claude-sonnet-4-6"

_SYSTEM_PROMPT = """\
You are a security advisor for EvidencePlane, a deterministic governance platform for AI-generated engineering work.

A policy engine has already produced a final verdict (allow/review/block). Your role is ADVISORY ONLY.

You must:
- Explain the policy violations in plain, developer-friendly language
- Suggest concrete remediation steps for each violation
- Draft a short resolution note that a human reviewer can edit and use

You must NEVER:
- Approve or reject any code change
- Override or criticize the policy verdict
- Claim authority to resolve or dismiss the case

Respond with a JSON object (no markdown, no code fences) matching exactly this schema:
{
  "verdict_explanation": "<plain-language explanation of why this was flagged>",
  "suggested_fixes": [
    {"violation_code": "<CODE>", "suggestion": "<concrete fix>"}
  ],
  "draft_resolution_note": "<short note a reviewer can edit and post>"
}
"""

_ADVISORY_WARNING = (
    "This suggestion is non-authoritative and was generated by an AI advisor. "
    "A human reviewer must make the final decision."
)


def _build_context_bundle(case: Case, run: Run) -> dict:
    tests = run.tests or []
    passed = sum(1 for t in tests if t.get("status") == "passed")
    failed = sum(1 for t in tests if t.get("status") == "failed")
    skipped = sum(1 for t in tests if t.get("status") == "skipped")

    scanner_summary = [
        {"finding_type": r.get("finding_type"), "severity": r.get("severity")}
        for r in (run.scanner_results_json or [])
    ]

    return {
        "decision": run.decision,
        "repo_name": run.repo_name,
        "branch": run.branch,
        "case_type": case.case_type,
        "severity": case.severity,
        "violations": [
            {"code": v.code, "message": v.message, "severity": v.severity}
            for v in run.violations
        ],
        "changed_files": [
            {"path": f.get("path"), "classification": f.get("classification")}
            for f in (run.changed_files or [])
        ],
        "tests_summary": {
            "total": len(tests),
            "passed": passed,
            "failed": failed,
            "skipped": skipped,
        },
        "scanner_findings_summary": scanner_summary,
    }


def _sha256_of(data: dict) -> str:
    payload = json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(payload.encode()).hexdigest()


def _call_llm(api_key: str, context_bundle: dict) -> dict:
    import anthropic

    user_message = (
        "Here is the governance context for this case:\n\n"
        + json.dumps(context_bundle, indent=2)
        + "\n\nProvide your advisory analysis as JSON."
    )
    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model=_MODEL_VERSION,
        max_tokens=1024,
        system=_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}],
    )
    raw = message.content[0].text.strip()
    return json.loads(raw)


def request_advisor_finding(
    session: Session,
    case_id: UUID,
    api_key: str,
) -> AdvisorFindingResponse:
    case = session.scalar(
        select(Case)
        .where(Case.id == case_id)
        .options(selectinload(Case.advisor_findings))
    )
    if case is None:
        raise EvidencePlaneError(404, "not_found", "Case not found.")
    if case.case_type not in ("review_required", "blocked_change"):
        raise EvidencePlaneError(
            422, "advisor_not_applicable", "Advisor only runs for review/block cases."
        )

    run = session.scalar(
        select(Run)
        .where(Run.id == case.run_id)
        .options(selectinload(Run.violations))
    )
    if run is None:
        raise EvidencePlaneError(503, "service_unavailable", "Run not found for case.")

    context_bundle = _build_context_bundle(case, run)
    prompt_sha256 = _sha256_of(context_bundle)

    try:
        output = _call_llm(api_key, context_bundle)
    except Exception as exc:
        raise EvidencePlaneError(
            502, "advisor_unavailable", f"Advisor LLM call failed: {exc}"
        ) from exc

    output["is_advisory"] = True
    output["advisory_warning"] = _ADVISORY_WARNING

    finding = AdvisorFinding(
        id=uuid4(),
        case_id=case_id,
        model_provider=_MODEL_PROVIDER,
        model_version=_MODEL_VERSION,
        prompt_sha256=prompt_sha256,
        output_json=output,
        created_at=utc_now(),
    )
    session.add(finding)
    session.commit()
    session.refresh(finding)
    return _to_response(finding)


def list_advisor_findings(session: Session, case_id: UUID) -> list[AdvisorFindingResponse]:
    case = session.get(Case, case_id)
    if case is None:
        raise EvidencePlaneError(404, "not_found", "Case not found.")
    findings = session.scalars(
        select(AdvisorFinding)
        .where(AdvisorFinding.case_id == case_id)
        .order_by(AdvisorFinding.created_at)
    ).all()
    return [_to_response(f) for f in findings]


def _to_response(finding: AdvisorFinding) -> AdvisorFindingResponse:
    output = finding.output_json
    return AdvisorFindingResponse(
        finding_id=finding.id,
        case_id=finding.case_id,
        model_provider=finding.model_provider,
        model_version=finding.model_version,
        prompt_sha256=finding.prompt_sha256,
        verdict_explanation=output.get("verdict_explanation", ""),
        suggested_fixes=output.get("suggested_fixes", []),
        draft_resolution_note=output.get("draft_resolution_note", ""),
        is_advisory=output.get("is_advisory", True),
        advisory_warning=output.get("advisory_warning", _ADVISORY_WARNING),
        created_at=finding.created_at,
    )
